config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("schedules/", include("schedules.urls")),
    path("admin/", admin.site.urls),
    # Authentication URLs
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
]

if settings.DEBUG and not settings.TESTING:
    urlpatterns += debug_toolbar_urls()

schedules/urls.py
from django.urls import path
from . import views

app_name = "schedules"

urlpatterns = [
    # Add URL patterns here
    path("", views.MonthListView.as_view(), name="index"),
    path("<int:id>/", views.MonthView.as_view(), name="month_view"),
    path("create/", views.create_schedule, name="create_schedule"),
    path(
        "<int:id>/generate",
        views.generate_schedule_assignments,
        name="generate_assignments",
    ),
    path("<int:id>/clear", views.clear_schedule, name="clear_schedule"),
    path("<int:id>/update", views.update_schedule, name="update_schedule"),
    path("<int:id>/pdf", views.pdf, name="pdf"),
]

schedules/views.py
from collections import defaultdict
import json
import pdfkit
from datetime import datetime
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.utils import timezone
from django.views import generic
from django.shortcuts import get_object_or_404, render
from django.contrib.auth import get_user_model
from config.settings import BASE_DIR
from schedules.models import Assignment, AssignmentStats, Schedule, Service, Task
from schedules.services.scheduler import Scheduler
from schedules.utils import (
    get_month_calendar,
    get_service_weeks,
)
from django.views.decorators.csrf import csrf_exempt
import os


class MonthView(generic.View):

    def get(self, request, id):
        schedule = Schedule.objects.get(id=id)

        year = schedule.date.year
        month = schedule.date.month
        month_calendar, month_name = get_month_calendar(year, month)

        # TODO consider moving these queries to ScheduleManager
        # Prefetch related objects to minimize queries

        # TODO check if we can prefetch tasks here
        services = Service.objects.prefetch_related(
            "tasks__users_with_preferences", "tasks__excludes"
        ).all()

        assignments = schedule.assignments.select_related(
            "task", "user", "task__service"
        )
        assignment_stats = AssignmentStats.objects.filter(
            schedule=schedule if assignments.count() > 0 else schedule.base_schedule
        ).select_related("task", "user")

        service_days = {service.day_of_week for service in services}
        service_weeks = get_service_weeks(month_calendar, service_days)

        # Collect assignment stats in a dictionary
        assignment_stats_map = {
            (stat.task.id, stat.user.pk): stat.assignment_delta
            for stat in assignment_stats
        }

        # Create a map of service_name to assignments for tasks in that service
        service_assignments = defaultdict(dict)
        for assignment in assignments:
            assignment_key = (
                f"{year}-{month}-{assignment.assigned_at.day}-{assignment.task.id}"
            )
            service_assignments[assignment.task.service.name][
                assignment_key
            ] = assignment.user

        # create map of eligible users for each task sorted by assignment delta
        eligible_users_for_task = defaultdict(list)
        for service in services:
            for task in service.tasks.all():
                eligible_users = task.get_eligible_users()
                sorted_users = sorted(
                    eligible_users,
                    key=lambda user: assignment_stats_map.get((task.id, user.pk), 1),
                )
                eligible_users_for_task[task.id] = sorted_users
        eligible_users_for_task.default_factory = None

        context = {
            "year": year,
            "month": month,
            "services": services,
            "month_name": month_name,
            "service_days": service_days,
            "service_weeks": service_weeks,
            "service_assignments": service_assignments,
            "eligible_users_for_task": eligible_users_for_task,
            "col_span": len(service_weeks) + len(service_weeks) + 1,
        }
        return render(request, "schedules/month_schedule.html", context)

    def post(self, request, year, month):
        """
        save assignments, mark as draft until commit?
        """
        pass


class MonthListView(generic.ListView):
    template_name = "schedules/month_list.html"
    context_object_name = "schedules"

    def get_queryset(self):
        return Schedule.objects.all().order_by("-date")


# TODO add csrf
@csrf_exempt
def generate_schedule_assignments(request, id):
    if request.method == "POST":
        schedule = Schedule.objects.get(id=id)
        services = Service.objects.prefetch_related(
            "tasks__users_with_preferences", "tasks__excludes"
        ).all()

        # parse results from schedule and send to generate
        # Could also take assignments from schedule itself
        assignment_map = json.loads(request.body) or {}

        scheduler = Scheduler(schedule, services, assignment_map)
        result, assignment_map = scheduler.solve()
        print(f"schedule result: {result}")

        update_assignments_in_schedule(schedule, assignment_map)

        return JsonResponse({"result": result, "assignment_map": assignment_map})


def update_assignments_in_schedule(schedule: Schedule, assignment_map: dict[str, str]):
    """update assignments in database"""
    # extract first names and last names from assignment map
    first_names = []
    last_names = []
    assignment_to_delete = []

    # filter out bad inputs:
    for date_task_str, user_name_inverted in assignment_map.items():
        if user_name_inverted is None:
            assignment_to_delete.append(date_task_str)
        elif "," not in user_name_inverted:
            # TODO let frontend detect partial user  name input
            # partial input save, let next save do update
            del assignment_map[date_task_str]
        else:
            first_names.append(user_name_inverted.split(", ")[1])
            last_names.append(user_name_inverted.split(", ")[0])

    # get users in batch, create map of user inverted name to user
    # TODO filter by group
    # TODO there is a better way to do this
    users = get_user_model().objects.filter(
        first_name__in=first_names, last_name__in=last_names
    )
    user_map = {user.inverted_name(): user for user in users}

    # get tasks in batch, create map of task id to task
    # TODO add schedule to service model
    # TODO get tasks from schedule's services
    tasks = Task.objects.all()
    task_map = {task.id: task for task in tasks}

    for date_task_str in assignment_to_delete:
        date_and_task_id = date_task_str.rsplit("-", 1)
        date_str = date_and_task_id[0]
        task_id = date_and_task_id[1]
        task = task_map[task_id]
        print(f"deleting assignment {date_task_str}")
        Assignment.objects.filter(
            schedule=schedule,
            task=task,
            assigned_at=datetime.strptime(date_str, "%Y-%m-%d").replace(
                tzinfo=timezone.get_current_timezone()
            ),
        ).delete()

    for date_task_str, user_name_inverted in assignment_map.items():
        if user_name_inverted:
            date_and_task_id = date_task_str.rsplit("-", 1)
            task_id = date_and_task_id[1]
            date_str = date_and_task_id[0]
            user = user_map[user_name_inverted]
            task = task_map[task_id]
            date = datetime.strptime(date_str, "%Y-%m-%d").replace(
                tzinfo=timezone.get_current_timezone()
            )
            assignment, created = Assignment.objects.update_or_create(
                schedule=schedule,
                task=task,
                assigned_at=date,
                defaults={"user": user},
            )
            # if created:
            #     print(f"created assignment {assignment}")
            # else:
            #     print(f"updated assignment {assignment}")


# TODO add csrf
@csrf_exempt
def update_schedule(request, id):
    """update assignments in database"""
    if request.method == "PUT":
        assignment_map = json.loads(request.body) or {}
        schedule = Schedule.objects.get(id=id)
        print(f"update schedule: {assignment_map}")
        if not schedule:
            print("schedule not found")
            return JsonResponse({"success": False, "error": "Schedule not found"})

        if assignment_map:
            update_assignments_in_schedule(schedule, assignment_map)

        return JsonResponse({"success": True}, status=204)
    return JsonResponse({"success": False}, status=405)


# TODO move views into their own files
@csrf_exempt
def pdf(request, id):
    if request.method == "GET":
        schedule = Schedule.objects.get(id=id)

        year = schedule.date.year
        month = schedule.date.month
        month_calendar, month_name = get_month_calendar(year, month)

        # TODO consider moving these queries to ScheduleManager
        # Prefetch related objects to minimize queries
        # TODO ask about how reusable bits of view context are encapsulated in django

        # TODO check if we can prefetch tasks here
        services = Service.objects.all()

        assignments = schedule.assignments.select_related(
            "task", "user", "task__service"
        )

        service_days = {service.day_of_week for service in services}
        service_weeks = get_service_weeks(month_calendar, service_days)

        # Create a map of service_name to assignments for tasks in that service
        service_assignments = defaultdict(dict)
        for assignment in assignments:
            assignment_key = (
                f"{year}-{month}-{assignment.assigned_at.day}-{assignment.task.id}"
            )
            service_assignments[assignment.task.service.name][
                assignment_key
            ] = assignment.user

        # Read the CSS file
        app_static_dir = os.path.join(BASE_DIR, "schedules", "static", "schedules")
        css_path = os.path.join(app_static_dir, "schedule.css")

        if os.path.exists(css_path):
            with open(css_path, "r") as f:
                css_content = f.read()
        else:
            # Fallback to empty CSS if file not found
            css_content = ""

        context = {
            "year": year,
            "month": month,
            "month_name": month_name,
            "services": services,
            "service_days": service_days,
            "service_weeks": service_weeks,
            "service_assignments": service_assignments,
            "css_content": css_content,
            "col_span": len(service_weeks) + len(service_weeks) + 1,
        }
        html_content = render(

schedules/templates/schedules/assignment_cell.html
{% comment %} TODO Extract styles into a css file {% endcomment %}
<td class="duty-cell" draggable="true" data-duty="{{assignment_key}}">
    <div style="position: relative;">
        {% if user %}
            <input class="assignment-input keep-datalist" type="text" list="{{task.id}}" value="{{user.last_name}}, {{ user.first_name }}" placeholder="{{user.last_name}}, {{ user.first_name }}">
        {% else %}
            <input class="assignment-input keep-datalist" type="text" list="{{task.id}}" value="">
        {% endif %}
        <div style="position: absolute; display: flex; right: 5px; bottom: 1px;">
        </div>
    </div>
</td>

schedules/templates/schedules/month_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Schedules{% endblock %}

{% block page_title %}Schedules{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'schedules/schedules.css' %}">
{% endblock %}

{% block content %}

<button onclick="document.getElementById('newScheduleDialog').showModal()">Create New Schedule</button>

{% if schedules %}
    <ul>
    {% for schedule in schedules %}
        <li>
            <a href="{% url 'schedules:month_view' id=schedule.id %}">
                {{ schedule.name }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No schedules are available.</p>
{% endif %}

<dialog id="newScheduleDialog">
    <h2>Create New Schedule</h2>
    <form method="POST" action="{% url 'schedules:create_schedule' %}">
      {% csrf_token %}
      <div>
        <label for="name">Name</label>
        <input type="text" id="name" name="name" required>
      </div>
      <div>
        <label for="description">Description</label>
        <textarea id="description" name="description" rows="3"></textarea>
      </div>
      <div>
        <label for="date">Date</label>
        <input type="date" id="date" name="date" required>
      </div>
      <div>
        <label for="base_schedule">Base Schedule</label>
        <select id="base_schedule" name="base_schedule">
          <option value="">None</option>
          {% for schedule in schedules %}
            <option value="{{ schedule.id }}">{{ schedule.name }}</option>
          {% endfor %}
        </select>
      </div>
      <div>
        <button type="button" onclick="document.getElementById('newScheduleDialog').close()">Cancel</button>
        <button type="submit">Create Schedule</button>
      </div>
    </form>
  </dialog>
{% endblock %}

schedules/templates/schedules/month_schedule.html
{% load schedule_tags %}
{% load static %}

{% comment %}
This template expects the following context variables:
- calendar: A list of weeks, where each week is a list of days
- service_days: A set of days that have services
- num_services: The maximum number of services needed
- TODO complete list of context variables
{% endcomment %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="pdfkit-page-size" content="Legal"/>
    <meta name="pdfkit-orientation" content="Landscape"/>
    <meta http-equiv="Cache-control" content="no-cache, no-store, must-revalidate">
    <meta http-equiv="Pragma" content="no-cache">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
            crossorigin="anonymous">
    </script>
    <title>{{ month_name }} {{ year }} Schedule</title>
    <link rel="stylesheet" href="{% static 'schedules/schedule.css' %}">
    <script src="{% static 'schedules/schedule.js' %}"></script>
</head>
<body>
    <div class="overlay mouse-reveal">
        <button id="generate-assignments">Generate Assignments</button>
        <button id="download-pdf">Download PDF</button>
        <button id="toggle-assignment-count">Toggle Assignment Counts</button>
        <button id="clear-schedule">Clear Assignments</button>
    </div>
    <div class="header">
        <h1>{{ month_name }}</h1>
    </div>
{%block content%}
<table>
    {% include "schedules/month_schedule_header.html" with service=services.0 %}
    {% include "schedules/month_schedule_service.html" with service=services.0 %}
    {% include "schedules/month_schedule_banner.html" with service=services.1 %}
    {% include "schedules/month_schedule_service.html" with service=services.1 %}
    {% include "schedules/month_schedule_header.html" with service=services.2 %}
    {% include "schedules/month_schedule_service.html" with service=services.2 %}
    {% include "schedules/month_schedule_service.html" with service=services.3 %}
</table>

<div class="toast" id="toast"></div>
<div class="assignment-map hidden"></div>

{% include "schedules/month_schedule_datalists.html" %}

{%endblock%}
</body>
</html>

schedules/templates/schedules/month_schedule_banner.html
{% block content %}
<td class="banner dark-background" colspan="{{ col_span }}">
    {{ service.name }}
</td>
{% endblock %}

schedules/templates/schedules/month_schedule_datalists.html
{% load schedule_tags %}
{% block content %}

{% for task_id, eligible_users in eligible_users_for_task.items %}
<datalist id="{{ task_id }}">
    {% for user in eligible_users %}
        <option value="{{ user.last_name }}, {{ user.first_name }}">{{ user.last_name }}, {{ user.first_name }}</option>
    {% endfor %}
</datalist>
{% endfor %}
{% endblock %}

schedules/templates/schedules/month_schedule_header.html
{% load schedule_tags %}

<thead>
    <th class="service-name">{{ service.name }}</th>
        {% for week in service_weeks %}
        {% with day=week|get_item:service.day_of_week %}
            {% if day %}
                <th class="empty"></th><th class="day">{{ day }}</th>
            {% else %}
                <th class="empty"></th><th class="empty"></th>
            {% endif %}
        {% endwith %}
    {% endfor %}
</thead>

schedules/templates/schedules/month_schedule_service.html
{% load schedule_tags %}

<tbody>
    {% for task in service.tasks.all %}
        <tr>
            <td>{{ task.name }}</td>
            {% for week in service_weeks %}
                {% get_service_day week service_days service.day_of_week as day %}
                {% if day %}
                    {% with assignment_key=year|addstr:"-"|addstr:month|addstr:"-"|addstr:day|addstr:"-"|addstr:task.id %}
                        {% if service_assignments|get_item:service.name|get_item:assignment_key %}
                            {% with user=service_assignments|get_item:service.name|get_item:assignment_key %}
                            <td class="empty"></td>
                            {% include "schedules/assignment_cell.html" with assignment_key=assignment_key %}
                            {% endwith %}
                        {% else %}
                            <td class="empty"></td>
                            {% with user=None %}
                                {% include "schedules/assignment_cell.html" with assignment_key=assignment_key %}
                            {% endwith %}
                        {% endif %}
                    {% endwith %} 
                {% else %}
                    <td class="empty"></td>
                    <td class="invalid-duty-cell"></td>
                {% endif %}
            {%endfor %}
        </tr>
    {% endfor %}
</tbody>

schedules/templates/schedules/pdf_month_schedule.html
{% load schedule_tags %}
{% load static %}

{% comment %}
This template expects the following context variables:
- calendar: A list of weeks, where each week is a list of days
- service_days: A set of days that have services
- num_services: The maximum number of services needed
- TODO complete list of context variables
{% endcomment %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="pdfkit-page-size" content="Legal"/>
    <meta name="pdfkit-orientation" content="Landscape"/>
    <meta http-equiv="Cache-control" content="no-cache, no-store, must-revalidate">
    <meta http-equiv="Pragma" content="no-cache">
    <title>{{ month_name }} {{ year }} Schedule</title>
    <style>
        {{ css_content|safe }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ month_name }}</h1>
    </div>
{%block content%}
<table>
    {% include "schedules/month_schedule_header.html" with service=services.0 %}
    {% include "schedules/month_schedule_service.html" with service=services.0 %}
    {% include "schedules/month_schedule_banner.html" with service=services.1 %}
    {% include "schedules/month_schedule_service.html" with service=services.1 %}
    {% include "schedules/month_schedule_header.html" with service=services.2 %}
    {% include "schedules/month_schedule_service.html" with service=services.2 %}
    {% include "schedules/month_schedule_service.html" with service=services.3 %}
</table>
{%endblock%}
</body>
</html>